### PR TITLE
[fix] Add babelify to support non-es6 browsers

### LINKED ISSUE #5: Doesn't work in Safari
Using the example program from the readme, this is the output in Safari:

screen shot 2015-11-04 at 13 04 27

This is the output in Chrome:

screen shot 2015-11-04 at 13 04 34

Looking in the Safari console I think I see the culprit:

screen shot 2015-11-04 at 13 06 24

### PR DESCRIPTION
**Pull request by emilbayes**
Should fix #5

### CODE REVIEW

**Comment by emilbayes** [comment]
Do I just press the merge button? :sweat_smile:

**Comment by AndreasMadsen** [comment]
I'm a bit busy, I will try to look at it wednesday.

**Comment by AndreasMadsen** [comment]
Lovely. I have confirmed that source mapping, it convert to ES5, works (except minor layout errors) in Safari.

**Comment by AndreasMadsen** [comment]
Published as 0.14.0

**Pull request merged**
