### PR TITLE
Online viewer

### PR DESCRIPTION
**Pull request by AndreasMadsen**
- [x] example
- [x] drop zone
- [x] github gits urls

### CODE REVIEW

**Comment by Fishrock123** [comment]
Hmm, many this should be on a different branch? I don't like having build bundles in repos much.

I also wonder if we need everything browserify is probably giving us more than we need and there are options to cut it down?

**Comment by AndreasMadsen** [comment]
> Hmm, many this should be on a different branch? I don't like having build bundles in repos much.

I agree. But know how to create a build system that uses files in the `master` branch and puts the build in `gh-pages`. It is also super annoying when developing, because one has to change branch between each edit and build.

> I also wonder if we need everything browserify is probably giving us more than we need and there are options to cut it down?

Just learned about something called `disk` :) Looks like it is mostly `pako` (ungzip)  and `d3`.  http://bl.ocks.org/andreasmadsen/1706c307a88867fe6f344f047ae34b82

**Comment by AndreasMadsen** [comment]
Added github gists support and ~~improved~~ implemented error handing. The only thing missing is the potential for bundle optimizations.

**Comment by AndreasMadsen** [comment]
I would love to find a better solution for storing build files in `gh-pages`, but from a `git` perspective its an anti-pattern so I'm not sure how to accomplice it without manually copying files.

**Pull request merged**
